# version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=/api

  backend:
    build: ./backend
    ports:
      - "3000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/journal_db}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 