# version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=/api

  backend:
    build: ./backend
    ports:
      - "3000:5000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb+srv://johnny194369672:qsbWWWPQiFUSeA8H@cluster0.oigb5.mongodb.net/journal_db?retryWrites=true&w=majority&appName=Cluster0

# Remove the volumes section since we don't need local MongoDB storage
# volumes:
#   mongodb_data: 

# networks:
#   app-network:
#     driver: bridge 